### ISSUE TITLE
page blanche

### ISSUE THREAD

**Issue by mecta02** [matt2210/Admin-Panel-Onset#2]
Bonjour jai souhaiter installer votre web panel mais page blanche :-( j'ai la derriere version de xampp mais autre site web fonctionne 

merci

**Comment by matt2210** [comment]
Hello 

Alors a tu bien rentrer les information de DB dans le fichier db.php ? 
Si oui le panel est-il situer a la racine htdocs de ton xampp ou il est dans un dossier genre /panel/ ? 

Merci

**Comment by mecta02** [comment]
quelle sont les infos a modifier dans le db.php ?
ces uniquement du local pour le moment 

https://pastebin.com/0ZxqqDmf

**Comment by matt2210** [comment]
il faut mdifier HOST et DBNAME 
https://i.imgur.com/7EyPucy.png

**Comment by mecta02** [comment]
quelle couill** désoler du dérangement  bravo pour ton taf 
<3

**Comment by matt2210** [comment]
Tkt sa arrive pas de probleme et merci ;)
