### ISSUE TITLE
Probléme import db

### ISSUE THREAD

**Issue by mecta02** [matt2210/Admin-Panel-Onset#3]
j'ai se mess a l'import de la db 

1 erreurs trouvées lors de l'analyse.
 Une parenthèse gauche suivie d'un ensemble de valeurs était attendus. (near "" at position 0)
Requête SQL :
INSERT INTO `users` (`id`, `user`, `password`, `rank`) VALUES (1, 'Admin', '$2y$10$UIKhYRd/CjTEsE8WhiHLE.SxBTcF6lSbzrwDha9pPhfWkFl35ze7a', '0'),
MySQL a répondu : Documentation
#1064 - Erreur de syntaxe près de '' à la ligne 2

**Comment by matt2210** [comment]
Humm bizzare normalement sa devrait pas posser de probleme tu utilise PHP my admin j'imagine ?

**Comment by mecta02** [comment]
oui oui

**Comment by matt2210** [comment]
0 problemes de mon coter la table se crée correctement

**Comment by mecta02** [comment]
php my admin refuse alor la enigme

**Comment by matt2210** [comment]
Tu est sur que la table ne se crée pas quand meme ?

**Comment by mecta02** [comment]
a certain jai verif

**Comment by mecta02** [comment]
https://www.noelshack.com/2020-02-3-1578507203-nouvelle-image-bitmap-3.png

**Comment by matt2210** [comment]
Bon chelou la table se crée mais rien n'est INSERT 

Vas dans la table et puis dans l'onglet SQL 

et tu copie colle sa 


```
INSERT INTO `users` (`id`, `user`, `password`, `rank`) VALUES
(1, 'Admin', '$2y$10$UIKhYRd/CjTEsE8WhiHLE.SxBTcF6lSbzrwDha9pPhfWkFl35ze7a', '0'),

**Comment by mecta02** [comment]
deja essayer camarade :-) mais meme erreur apres ces pour toi avancer sur se super projet

**Comment by matt2210** [comment]
c'est très bizzare bon écoute solution de secours tu fait un insert direct via l'onglet inseret et tu met les informations qu'il faut

**Comment by mecta02** [comment]
j'ai trouver la solution 

INSERT INTO `users` (`id`, `user`, `password`, `rank`) VALUES
(1, 'Admin', '$2y$10$UIKhYRd/CjTEsE8WhiHLE.SxBTcF6lSbzrwDha9pPhfWkFl35ze7a', '0');

il faut que tu remplace le " ," a la fin de la ligne 43 par un ";"

**Comment by matt2210** [comment]
Nikel alors 

Merci hesite pas a me faire des retours :)
